# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Check Manifests

on:
  push:
    branches: [main, dev, 1.0*, 2.0*, fasttrack/*]
  pull_request:
    branches: [main, dev, 1.0*, 2.0*, fasttrack/*]

permissions: read-all

jobs:
  build:
    name: Check Manifests
    runs-on: ubuntu-latest
    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
      with:
        egress-policy: audit

    - name: Check out code
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

    - name: Check x86_64 manifests
      run: |
        pushd toolkit
        make check-x86_64-manifests
        popd

    - name: Check aarch64 manifests
      run: |
        pushd toolkit
        make check-aarch64-manifests
        popd
      if: always()
