# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Livepatch specs check

on:
  push:
    branches: [2.0, fasttrack/*]
  pull_request:
    branches: [2.0, fasttrack/*]

permissions: read-all

jobs:
  spec-check:
    name: Livepatches check
    runs-on: ubuntu-latest

    steps:
      # Checkout the branch of our repo that triggered this action
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - name: Workflow trigger checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Setup Python 3.9
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: 3.9

      - name: Get Python dependencies
        run: |
          sudo apt-get install -y python3-rpm
          sudo python3 -m pip install -r toolkit/scripts/requirements.txt

      - name: Check livepatch specs are valid
        run: |
          export USER_EMAIL=test@test.com
          export USER_NAME=test

          .github/workflows/overwrite_shell_link.sh

          if ! toolkit/scripts/livepatching/update_livepatches.sh >/dev/null
          then
            echo "ERROR: failed to verify livepatch specs." >&2
            exit 1
          fi

          if [[ -z "$(git diff)" ]]
          then
            exit 0
          fi

          cat << EOF
          #################### CHECK FAILURE ####################
          Livepatch specs need to be updated!
          Run the following command to perform the update:

              toolkit/scripts/livepatching/update_livepatches.sh

          #################### CHECK FAILURE ####################
          EOF

          exit 1
